replicaCount: 1

image:
  repository: 718036735682.dkr.ecr.ap-northeast-2.amazonaws.com/hello-apps-greet
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 # FastAPI 포트