replicaCount: 1

image:
  # image 저장소의 위치는 ECR을 바라보도록함 ( ecr_for_apps 폴더 )
  # ecr주소/fortune
  repository: 718036735682.dkr.ecr.ap-northeast-2.amazonaws.com/hello-apps-fortune
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 # FastAPI 포트